version: '3.3'

services:
  spring-boot-service:
    image: akonjevic/docker-spring-boot:final
    ports:
      - 8080:8080
    depends_on:
      - db
      - node
    networks:
      - frontend
    
  db:
    image: akonjevic/postgresql2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: demodb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopass
    networks:
      - frontend

  node:
    image: akonjevic/docker-node:firsttry
    ports:
      - 8081:8081
    networks:
      - frontend

networks:
  frontend:
